### ISSUE TITLE
GUI displays IllegalArgumentException

### ISSUE THREAD

**Issue by J0B10** [codeoverflow-org/chatoverflow#122]
### Description
When building codeoverflow using the `feature/40-connector-metadata` branch the gui doesn't load and instead displays a stack trace of an IllegalArgumentException.

### How to reproduce
1. Checkout the `feature/40-connector-metadata` branch for framework, gui, api and plugins-public.

2. Run `[Advanced] Full Reload and Run ChatOverflow` Run Configuration

3. Drink some coffe as it takes forever

4. Open http://localhost:2400/

### Error Log 
```
java.lang.IllegalArgumentException: URI is not absolute
	at java.io.File.<init>(File.java:416)
	at org.codeoverflow.chatoverflow.ui.web.GUIServlet.$anonfun$new$1(GUIServlet.scala:41)
	at org.scalatra.ScalatraBase.liftAction(ScalatraBase.scala:280)
	at org.scalatra.ScalatraBase.$anonfun$invoke$1(ScalatraBase.scala:274)
	at org.scalatra.ScalatraBase.withRouteMultiParams(ScalatraBase.scala:351)
	at org.scalatra.ScalatraBase.withRouteMultiParams$(ScalatraBase.scala:347)
	at org.codeoverflow.chatoverflow.ui.web.GUIServlet.withRouteMultiParams(GUIServlet.scala:19)
	at org.scalatra.ScalatraBase.invoke(ScalatraBase.scala:273)
	at org.scalatra.ScalatraBase.invoke$(ScalatraBase.scala:272)
	at org.codeoverflow.chatoverflow.ui.web.GUIServlet.invoke(GUIServlet.scala:19)
	at org.scalatra.ScalatraBase.$anonfun$runRoutes$3(ScalatraBase.scala:248)
	at scala.Option.flatMap(Option.scala:171)
	at org.scalatra.ScalatraBase.$anonfun$runRoutes$1(ScalatraBase.scala:246)
	at scala.collection.immutable.Stream.flatMap(Stream.scala:486)
	at org.scalatra.ScalatraBase.runRoutes(ScalatraBase.scala:245)
	at org.scalatra.ScalatraBase.runRoutes$(ScalatraBase.scala:243)
	at org.codeoverflow.chatoverflow.ui.web.GUIServlet.runRoutes(GUIServlet.scala:19)
	at org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:169)
	at org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:181)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:199)
	at org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:181)
	at org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:150)
	at org.codeoverflow.chatoverflow.ui.web.GUIServlet.executeRoutes(GUIServlet.scala:19)
	at org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:123)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope.withResponse(DynamicScope.scala:79)
	at org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:77)
	at org.codeoverflow.chatoverflow.ui.web.GUIServlet.withResponse(GUIServlet.scala:19)
	at org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:59)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
	at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
	at org.codeoverflow.chatoverflow.ui.web.GUIServlet.withRequest(GUIServlet.scala:19)
	at org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:58)
	at org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:56)
	at org.codeoverflow.chatoverflow.ui.web.GUIServlet.withRequestResponse(GUIServlet.scala:19)
	at org.scalatra.ScalatraBase.handle(ScalatraBase.scala:123)
	at org.scalatra.ScalatraBase.handle$(ScalatraBase.scala:119)
	at org.codeoverflow.chatoverflow.ui.web.GUIServlet.org$scalatra$servlet$ServletBase$$super$handle(GUIServlet.scala:19)
	at org.scalatra.servlet.ServletBase.handle(ServletBase.scala:53)
	at org.scalatra.servlet.ServletBase.handle$(ServletBase.scala:46)
	at org.codeoverflow.chatoverflow.ui.web.GUIServlet.handle(GUIServlet.scala:19)
	at org.scalatra.ScalatraServlet.service(ScalatraServlet.scala:65)
	at org.scalatra.ScalatraServlet.service$(ScalatraServlet.scala:64)
	at org.codeoverflow.chatoverflow.ui.web.GUIServlet.service(GUIServlet.scala:19)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:833)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
	at java.lang.Thread.run(Thread.java:748)
```

### References
**Used commits:**
https://github.com/codeoverflow-org/chatoverflow/commit/a4fd191d1f677acb6bb30d579e9484063c106d3e  
https://github.com/codeoverflow-org/chatoverflow-api/commit/1cfad1fa939bc79881858fa07b76a8dbccc89fba  
https://github.com/codeoverflow-org/chatoverflow-gui/commit/fbfa2d92f8456d43a7979303e71fcfb51b9d5303  
https://github.com/codeoverflow-org/chatoverflow-plugins/commit/5a7108d03a7249eb4849ffd6134167770c754a99

**Comment by sebinside** [comment]
Unable to replicate.

**Comment by hlxid** [comment]
@joblo2213 judging based on your image of a working gui in discord this is no longer a problem correct?

**Comment by sebinside** [comment]
Probably yes. If a (new) problem occurs, we can have another look.

**Comment by J0B10** [comment]
Seems like this happens if the gui build process fails.
